language: haskell

ghc:
  - "8.6"

services:
  - docker

stages:
  - install
  - build
  - name: image
    if: branch = main AND type = push

before_install:
  # install librdkafka-dev
  - wget -qO - https://packages.confluent.io/deb/5.3/archive.key | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.3 stable main"
  - sudo apt-get update && sudo apt-get install librdkafka-dev

install:
  - cabal install happy-1.19.12 alex
  - cabal install c2hs
  - cabal install --only-dependencies --enable-tests --extra-include-dirs=/usr/local/include --extra-lib-dirs=/usr/local/lib

jobs:
  include:
    - stage: build
      name: Build and test striot
      script:
        - cabal configure --enable-tests && cabal build && cabal test
        - ./gen_test_makefile.sh > Makefile; make GHC="cabal exec ghc -- -XTemplateHaskell"
        - ./gen_test_makefile.sh > Makefile; make GHC="cabal exec ghc -- -XTemplateHaskell"
    - stage: image
      install: true
      name: Build striot-base docker image
      script:
        - make -C containers/
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push striot/striot-base:latest
