= Rewrites
Jonathan Dowland <jon.dowland@ncl.ac.uk>
:toc: right
:toclevels: 4

== Abstract

We describe STRIoT: a stream-processing system built around pure
functional programming principles. STRIoT supports the composition of a
stream processing pipeline from eight purely functional operators. The
STRIoT system is designed to rewrite the supplied stream pipeline in
order to optimize its operation against a set of functional and
non-functional requirements. We compile a list of rewrite rules based on
a systematic pairwise comparison of the functional operators. We
classify each rule as total if it can be applied in any circumstance, or
partial if there are requirements on the input stream not expressed by
the type of the stream, and quantify those requirements.

== Background

description of striot
selection of operators

A *Stream* is a list of *Event*s. An *Event* has an Id field and might include an
iota of data, (a datum?) and a timestamp.

<table of operators>

    streamFilter    :: (a -> Bool) -> Stream a -> Stream a
    streamMap       :: (a -> b) -> Stream a -> Stream b
    streamFilterAcc :: (b -> a -> b) -> b -> (a -> b -> Bool) -> Stream a -> Stream a
    streamScan      :: (b -> a -> b) -> b -> Stream a -> Stream b
    streamWindow    :: Stream a -> Stream [a]
    streamExpand    :: Stream [a] -> Stream a
    streamMerge     :: [Stream a] -> Stream a
    streamJoin      :: Stream a -> Stream b -> Stream (a,b)

Ignoring the stream-in, stream-out parameters, the first four operators are
unary and their functional parameter operates on the payload of the stream,
and not the stream itself (the types of the HoFs do not include Stream)

The second set of four operators operate directly on Streams.

== Method

We constructed a list of operator pairs and considered each pair in
sequence in order to systematically explore all possible combinations.
For each pair, we initially attempted to reverse the order of the
operators whilst preserving the functional result of their combination
on an input stream. For pairs of the same
operator, we attempt to construct an equivalent, single, fused operator.
For pairs of operators that are the dual of one another, we attempted to
eliminate them.

This method sometimes yielded a result that turned out not to behave
identically to the original pair in some or all circumstances. If we
thought the rewrite could still be useful in practise, we recorded it
with the appropriate annotation.

Once we had determined a viable rewrite rule, we examined whether its
inverse was a second, distinct viable rule.

=== Semantic analysis

`streamMap` and `streamFilter` are stream variants of the widely used
`map` and `filter` which have well understood semantics.

`streamWindow`, `streamExpand` and `streamJoin` manipulate the structure of the
stream itself: `streamWindow` eliminates the Event wrappers around the iotas
that flow into it and synthesises new ones for the collected iotes it outputs.
`streamExpand` is its dual. `streamJoin` eliminates two `Event` wrapper and
synthesises a new one containing a tuple.

For this reason, the following rewrite rule is not applicable
in all cases:

    streamExpand . streamWindow _ = id

This holds only in terms of the data encapsulated within the stream. But
since `streamWindow` discards the `Event` wrappers around the iotas flowing
into it, we lose the information contained therein, including the timestamp
field.

The type of `streamMerge` indicates that it could manipulate the input
*Event*s, but we know in practise that it doesn't.

=== Tools

Most of this exercise was conducted offline using pen and paper. For
some of the more complex rewrites, we sketched an outline on paper and
then attempted to encode the result in Haskell. Two Haskell libraries in
particular proved very useful for testing our work:
QuickCheck<<QuickCheck>> and
the Haskell Testing Framework<<HTF>>. Using these tools, we attempted to
construct a "property" that expressed the equivalence of the operator
pair before and after our rewrite. QuickCheck then generates a set of
randomly generated inputs and compares the output of each side of the
equation.

This provided some confidence that each rewrite rule was correct. It
also helped to catch a few cases where we had authored a rewrite rule we
thought was total, but wasn't. We then explored the failure cases to
determine whether the rule needed to be thrown out, or was useful in
some circumstances, in which case we noted the necessary caveats.

XXX "total" mentioned in the para above; but defined below

In order for QuickCheck to generate random Stream data, we were required
to provide a trivial implementation of the Arbitrary class for the
appropriate data type in STRIoT. This data type is higher-order, and so
to evaluate the properties, we needed to bind the type variables to
something concrete.  We chose `Char`, which has several nice properties:
it satisfies `Eq`, permitting the comparison of streams of `Chars`; it
satisfies `Ord`, simplifying the writing of predicates for
`streamFilter` and friends (we can use standard functions including `>=`
and `succ`).  Finally, when examining the output of operator-pairs in an
interactive session, `Char` is quite friendly to human eyes.

=== Describing rewrites

==== total/partial

We describe a rewrite as total if it can be applied to any occurance of
the pattern. Some rewrites are only applicable if some other properties
of the stream hold. These properties are not expressed in the definition
or type of the rewrite function. Indeed they may not be expressible due
to the limits of the type system.

An example of a partial rewrite rule might be one that does not guarantee that
the ordering of the input Events is preserved in the rewritten version.
Another is the elimination of adjacent window/expand operations, which result
in the loss of the timestamp and id metadata from the input Events.  In both
cases whether these are important considerations is application-specific.

== TODO

Classification of non-order-preserving rewrites: whether the re-ordering
is determined *internally* or *externally*. Internally means that
the re-ordering is entirely determined by the composition of stream
operators; external means that it is dependent on one of the externally
supplied arguments, such as the predicate supplied to streamFilter.

== Results

     1. `streamFilter f . streamFilter g = streamFilter (\x -> f x && g x)`
        total; fusion

     2. `streamFilter p2 . streamFilterAcc accfn acc p1
         = streamFilterAcc accfn1 acc1 (\x a -> p1 x a && p2 x)`
        total; fusion

     3. `streamFilterAcc accfn acc p2 . streamFilter p1 =
         = streamFilterAcc (\a v -> if p1 v then accfn a v else a)
         acc
         (\x a -> p1 x && p2 x a)`
        total; fusion

     4. `streamFilterAcc accfn2 acc2 p2 . streamFilterAcc accfn1 acc1 p1
         = streamFilterAcc
           (\(x,y) v -> (accfn1 x v, if p1 v x then accfn2 y v else y))
           (acc1,acc2)
           (\x (y,z) -> p1 x y && p2 x z)`
        total; fusion

     5. `streamFilter p . streamMap f = streamMap f . streamFilter (p . f)`
        total.
        efficiency of RHS:
        If p is highly selective, then the overhead of evaluating f
        twice per selected event may be lower than the savings made by
        reducing the list de/reconstruction overhead of streamMap.

     6. `streamMap f . streamMap g = streamMap (f . g)`
        total; fusion

     7. `streamJoin s1 . streamMap f = streamMap (\(x,y) -> (x, f y)) .  streamJoin s1`
        total

    8. `streamFilter f . streamExpand = streamExpand . streamMap (filter f)`
        total.

    9. `streamMap f . streamExpand = streamExpand . streamMap (map f)`
        total.

    10. `streamMap f $ streamMerge [s1, s2]
        = streamMerge [streamMap f s0, streamMap f s2]`
        total.

    11. `streamMerge [s1, streamMerge [s2, s3]]
        = streamMerge [s0, s2, s3]`
        total
        ordering preserved in the right-associative case

    12. `streamFilterAcc af a p . streamMap f
        = streamMap f . streamFilterAcc af a (p . f)`
        total

=== Inverted rules

When the above rules were derived, each was analysed to determine
whether it could be inverted: whether any occurence of a stream matching
the pattern on the right could be replaced with that on the left.

The following rules are inverted versions of the above, but are subject to a
*decomposition caveat*: The arguments to the stream operators on
the left hand side of these rules are *compound expressions*, that are
decomposed and their constituent expressions used on the right-hand side.

When we are considering a practical system of applying such rules to a
Stream Graph, it is unlikely that we are going to be able to decompose or
inspect the composition of the functional arguments, so these rules may
be of limited practical use.

[start=13]
    13. `filter (\x -> f x && g x) = filter f . filter g`

    14. `streamMap f . streamFilter (p . f) = streamFilter p . streamMap f`

    15. `streamMap (f . g) = streamMap f . streamMap g`

    16. `streamMap (\(x,y) -> (x, f y)) . streamJoin s1 = streamJoin s1 . streamMap f`

    17. `streamExpand . streamMap (filter f) = streamFilter f .  streamExpand`
        (XXX it would be good to write QuickCheck properties for the inversions)

    18. `streamExpand . streamMap (map f) = streamMap f . streamExpand`

    19. `streamMap f . streamFilterAcc af a (p . f)
        = streamFilterAcc af a p . streamMap f`

==== inverted `streamMerge` rules

The semantics of `streamMerge` are unique amongst the stream operators, given
its unique type signature.

XXX expand

[start=20]
    20. `streamMerge [streamMap f s1, streamMap f s2]
        = streamMap f $ streamMerge [s-2, s2]`

    XXX this is kind of a special case of the composition caveat?

    21. `streamMerge [s1, s2, s3]
        = streamMerge [s1, streamMerge [s2, s3]]`

=== Partial rules

The following rules do not preserve the metadata contained within the Event
structures. XXX what do they do to "empty" events? I.e. Nothing instead of
a datum? are they discarded in the window function?

[start=22]
     22. `streamExpand . streamWindow _ = id`

     23. `streamWindow w . streamMap f = streamMap (map f) . streamWindow w`
        
        only works if streamWindow predicate does not look at value:
        window (>=3) . map (+1) [1,2,3,4] ≠ map (+1) . window (>=3) [1,2,3,4]
        otoh that's not a valid windowmaker either.

The following partial rules do not preserve the order of stream events:

[start=24]
    24. `streamMerge [streamExpand s1, streamExpand s2]
        = streamExpand (streamMerge [s1,s2])`

    25. `streamExpand (streamMerge [w1,w2])
        = streamMerge [streamExpand w1, streamExpand w2]`

and their inverses

[start=26]
    26. `streamFilter f $ streammerge [s1, s2]
        = streamMerge [streamFilter f s1, streamFilter f s2]`

    27. `streamMerge [streamFilter f s1, streamFilter f s2]
        = streamFilter f $ streammerge [s1, s2]`

There are some issues to consider about constant or variable size of
lists in the case where the stream data type is a list, such as after
a streamWindow operator. In the case of streamWindow, the output list
size will be constant, but this is not reflected in the type.
(XXX: where does this matter?)

=== Summary

14 rules
23 adding inversions (with caveats)
27 adding partial rules that do not preserve re-ordering

It appears to not be possible to perform the same promotion/fusion trick
with streamScan as streamFilterAcc (XXX: Why?)

=== join

For pairs where the first operator is join, we know that the second
must operate on a tuple. However we cannot use this information to
decompose the arguments to higher order functions (filter or map), so in
general it seems no useful rewrites exist for this category of pairs.

== Conclusion

There are 64 pairings of 8 functional operators. Systematically looking
for ways to rewrite each pair whilst preserving the functional
definition yielded up to 27 rewrite rules: 12 rules classified as
applicable in any circumstance (total), a further 7 with caveats
discovered by testing for inversions of the first 12, and a further
8 partial rules that apply if certain external properties of the stream
apply (such as, strict order not being important)

These rules may prove useful as a base set of possible rewrites that
could be applied to a stream processing graph in order to change and/or
optimise the non-functional behaviour of the graph.

Examination of the rules, in particular the partial rules, has revealed
some properties of the graphs that, if encoded and provided to a rewrite
system, could aid in making more effective rewriting decisions. For
example if strict ordering of stream events is not important, then a
further 6 rewrite rules could be applied.

=== Further work

 * looking at triples or other combinations of operators
 * factoring in consideration of partitions
 * selection and encoding of additional information about streams for
   rewrite purposes

[bibliography]
== References

- [[[QuickCheck]]]
- [[[HTF]]]
