# consumer via streamMerge
node3:
  build: node3
  stdin_open: true
  tty: true

# first producer
node2:
  build: node2
  stdin_open: true
  tty: true
  links:
    - node3

# second producer
node1:
  build: node1
  stdin_open: true
  tty: true
  links:
    - node3
